CouncilTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from api import views as api_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls', namespace="login")),
    path('api/', include('api.urls')),
]

from django.conf.urls import (
    handler404, handler500
)

handler404='login.views.page_not_found'
handler500='login.views.server_error_page'

api/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from api.views import StudentViewSet, UserViewSet
from rest_framework import renderers
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'students', views.StudentViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'unbrellas', views.UnbrellaViewSet)
router.register(r'batteries', views.BatteryViewSet)
router.register(r'lans', views.LanViewSet)
router.register(r'studytables', views.StudyTableViewSet)
router.register(r'complains', views.ComplainViewSet)
router.register(r'cables', views.CableViewSet)
router.register(r'Loggings', views.LoggingViewSet)


urlpatterns = [
    path('api-auth/', include('rest_framework.urls')),
    path('', include(router.urls)),
]

login/urls.py
from django.urls import path
from login import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from login.forms import custom_login_form
from django.views.static import serve
from . import models

app_name = 'login'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login/login.html', form_class=custom_login_form), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.Main, name='main'),
    path('mypage/', views.MyPage, name='mypage'),
    path('reservation/', views.StudyTableClass.LendTable, name='seltable'),
    path('reservation/submit', views.StudyTableClass.TableSelect, name='lendtable'),
    path('password_change/', views.PasswordChangeView.as_view(template_name='login/change_pw.html'), name='change'),
    path('first_login/', views.first_login_class.as_view(template_name='login/login_agreement.html'), name='first'),
    path('password_complete', views.PasswordChangeDoneView.as_view(), name='change_done'),
    path('pc/', views.PasswordChangeView.as_view(template_name='login/pass_change.html'), name='ch'),
    path('jong/', views.GetComplain, name='jong'),
    path('lendun/', views.LendUn, name='jong'),
    path('ca/', views.create_all_password),
    path('complain/', views.GetComplain),
    path('jong1/',views.EveryHourStudyTable),
    path('jong2/',views.EveryDayStudyTable),
    path('password_reset/',views.password_reset,name='password_reset'),
    path('pass_changed', views.pass_changed, name='pass_changed'),
    path('expired', views.ExpiredCheck),
    path('manage/rental/', views.ManageRentalView.as_view(), name='manage_rental'),
    path('manage/rental/<str:model>/<int:pk>/', views.ItemDetailView.as_view(), name='item_detail'),
    path('manage/rental/update/<str:model>/<int:pk>/', views.ItemUpdateView.as_view(), name='item_update'),
    path('manage/rental/delete/<str:model>/<int:pk>/', views.item_delete, name="item_delete"),
    path('manage/', views.manage_view, name='manage'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

software-final/HBW/login/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('<int:pk>/edit/', views.UserEdit, name='user_edit'),
    path('<int:pk>/show/', views.UserShow, name='user_show'),
]

login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator
from rest_framework.exceptions import APIException, ValidationError
from django.db import IntegrityError
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.models import AbstractUser
from api.models import Logging

# Create your models here.

# 대여 (학생회 측)
# 예약 (학생 측)

class Student(models.Model):    
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user_data', null=True, blank=True)
    # 장고의 User모델에서 username(학번 즉 ID), password first_name, last_name, user_permissions, last_login을 사용
    # user 모델의 필드들
        # username
        # first_name
        # last_name
        # email (Optional)
        # password (Required. A hash of, and metadata about, the password. (Django doesn’t store the raw password.) Raw passwords can be arbitrarily long and can contain any character. See the password documentation.)
        # groups
        # user_permissions
        # is_staff (Boolean)
        # is_active (Boolean)
        # is_superuser (Boolean)
        # last_login (A datetime)
        # date_joined (A datetime)

    std_year = models.CharField(max_length = 8) 
    # 17, 18 등 입학 년도 저장

    is_paid = models.BooleanField(default = False)
    # 회비 납부 여부

    A4_count = models.PositiveIntegerField(default = 0, validators=[MaxValueValidator(50)], error_messages={'max_value' : '하루 대여량은 50장을 넘길 수 없습니다.'})
    # 현재 빌리려 하는 A4 매수

    today_A4 = models.PositiveIntegerField(default = 0,  validators=[MaxValueValidator(50)], error_messages={'max_value' : '하루 대여량은 50장을 넘길 수 없습니다.'})
    # 오늘 수령한 A4 매수

    month_A4 = models.PositiveIntegerField(default = 0,  validators=[MaxValueValidator(500)], error_messages={'max_value' : '한달 대여량은 500장을 넘길 수 없습니다.'})
    # 이번달 수령한 A4 매수

    is_attend = models.BooleanField(default = True)
    #재학여부

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        self.today_A4 = self.today_A4 + self.A4_count
        if self.today_A4 > 50:
            raise APIException("하루 대여량은 50장을 넘길 수 없습니다!")
        self.month_A4 = self.month_A4 + self.A4_count
        if self.month_A4 > 500:
            raise APIException("한달 대여량은 500장을 넘길 수 없습니다!")
        self.A4_count = 0

        Logging.objects.create(
            item = "today_A4", 
            manager = now_time_table.objects.first().name,
            user = self.user.username,
            message = "A4 "+str(self.A4_count)+"장 대여")
        
        super().save(*args, **kwargs)

    objects = models.Manager()


class RentalItem(models.Model):
    status_available = '대여가능'
    status_borrowed = '대여중'
    status_unavailable = '대여불가'
    status_reserved = '대여신청중'
    status_choices = (
        (status_available, '대여가능'),
        (status_borrowed, '대여중'),
        (status_unavailable, '대여불가'),
        (status_reserved, '대여신청중'),
    )
    is_borrowed = models.BooleanField(default = False)
    borrowed_time = models.DateTimeField(auto_now_add=True)
    is_reserved = models.BooleanField(default = False)
    reservation_time = models.DateTimeField(auto_now_add=True)
    status=models.CharField(max_length=5, choices=status_choices, default=status_available)
    ex_lender = models.CharField(max_length=9, default = "", null=True, blank=True)
    item_name = ""

    def __str__(self):
        count = ""
        if self.number == 1:
            count = "st "
        elif self.number == 2:
            count = "nd "
        else:
            count = "rd "
        return str(self.number) + count + self.item_name

    def save(self, *args, **kwargs):
        if self.status == self.status_unavailable: # status 가 "대여불가"일 경우! -> 이를 먼저 풀어줘야 한다!
            self.status = self.status_unavailable
            self.is_reserved = False
            self.is_borrowed = False
            if self.borrowed_by is not None:
                self.ex_lender = self.borrowed_by.user.username
            self.borrowed_by = None

        elif self.is_reserved == True and self.is_borrowed == False and self.borrowed_by is not None   or    self.ex_lender == "" and self.status == self.status_reserved and self.borrowed_by is not None: # "예약" 상태가 될 때 (조건1 : is_reserved 체크, is_borrowed 비체크, borrowed_by 존재!) or (조건2 : status가 "대여신청중"이고 borrowed_by가 존재!)
            self.status = self.status_reserved
            self.is_reserved = True
            self.is_borrowed = False
            #self.ex_lender = self.borrowed_by.user.username
            self.reservation_time = timezone.localtime()

        elif self.is_reserved == False and self.is_borrowed == True and self.borrowed_by is not None   or    self.status == self.status_borrowed and self.borrowed_by is not None: # "대여" 상태가 될 때 (조건1 : is_reserved 비체크, is_borrowed 체크, borrowed_by 존재!) or (조건2 : status가 "대여중"이고 borrowed_by가 존재!)
            if not self.ex_lender or self.ex_lender == self.borrowed_by.user.username :
                self.status = self.status_borrowed
                self.is_reserved = False
                self.is_borrowed = True
                self.borrowed_time = timezone.localtime()
                Logging.objects.create(
                    user = self.borrowed_by.user.username, 
                    manager = now_time_table.objects.first().name,
                    item = self.item_name,
                    message = self.__str__() +" 대여"
                    )
            else : 
                return 

        else : # "대여가능" 상태가 될 때, 즉 반납할 때 (조건 : is_reserved = False, is_borrowed = False, status = 대여가능)
            try:
                Logging.objects.create(
                    user = self.borrowed_by.user.username,
                    manager = now_time_table.objects.first().name,
                    item = item_name,
                    message =self. __str__() + " 반납"
                    )
            except:
                Logging.objects.create(
                    user = "blank",
                    manager = now_time_table.objects.first().name,
                    item = self.item_name,
                    message = self.__str__() +"예약 시간초과"
                    )            
            self.is_reserved = False
            self.is_borrowed = False
            self.status = self.status_available
            self.borrowed_by = None

        try :
            super().save(*args, **kwargs)
        except IntegrityError:
            self.borrowed_by = None
            raise APIException("같은 종류의 대여사업을 2개 이상 사용하실 수 없습니다!")
        

    def is_available(self):
        if self.status == self.status_available:
            return True
        else:
            return False


class Unbrella(RentalItem):
    borrowed_by = models.OneToOneField(Student, null=True, related_name = "un", blank=True, on_delete=models.CASCADE)
    item_name = "Umbrella"
    number = models.PositiveSmallIntegerField(primary_key=True, unique=True)
    class Meta:
        ordering = ['number']


#배터리 모델
class Battery(RentalItem):
    borrowed_by = models.OneToOneField(Student,related_name='ba', null=True, blank=True, on_delete=models.DO_NOTHING)
    return_time = models.DateTimeField(auto_now_add=True)
    item_name = "Battery"
    number = models.PositiveSmallIntegerField(primary_key=True, unique=True)
        

#랜선 모델
class Lan(RentalItem):
    borrowed_by = models.OneToOneField(Student, related_name='la', null=True, blank=True, on_delete=models.DO_NOTHING)
    return_time = models.DateTimeField(auto_now_add=True)
    item_name = "Lan"
    number = models.PositiveSmallIntegerField(primary_key=True, unique=True)

#케이블 모델, 오로지 하나의 케이블을 식별하기 위해선 number, cable_type이 필요하다 (차라리 타입말고, 번호로만 타입을 식별해본다?)
class Cable(RentalItem):
    type_c = 'C타입'
    type_5= '5핀'
    type_8 = '8핀'
    type_choices = (
        (type_c, 'C타입'),
        (type_5, '5핀'),
        (type_8, '8핀'),
    )
    item_name="Cable"
    number = models.PositiveSmallIntegerField(primary_key=True, unique=True)
    borrowed_by = models.OneToOneField(Student, related_name='ca', null=True, blank=True, on_delete=models.DO_NOTHING)
    cable_type = models.CharField(max_length=10, choices=type_choices, default=type_5)

    def __str__(self):
        count = ""
        if self.number == 1:
            count = "st "
        elif self.number == 2:
            count = "nd "
        else:
            count = "rd "
        return (str(self.number))+ count + "Cable(" + self.cable_type + ")"

class Hdmi(RentalItem):
    borrowed_by = models.OneToOneField(Student, related_name='hdmi', null=True, blank=True, on_delete=models.DO_NOTHING)
    return_time = models.DateTimeField(auto_now_add=True)
    item_name = "Hdmi"
    number = models.PositiveSmallIntegerField(primary_key=True, unique=True)
    
class Poster(models.Model):  
    title = models.CharField(max_length=100)
    photo = models.ImageField(blank=True)
    number = models.PositiveSmallIntegerField()


#실습실 테이블 모델
class StudyTable(models.Model):
    number = models.PositiveSmallIntegerField()
    is_borrowed = models.BooleanField(default = False)
    start_time = models.CharField(max_length=100, blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    lender = models.ForeignKey(Student, related_name='st', null=True, blank=True, on_delete=models.DO_NOTHING, db_constraint=False)
    is_checked = models.BooleanField(default = False)
    
    def save(self, *args, **kwargs):
        if self.is_borrowed:
            Logging.objects.create(
                user=self.lender.user.username,
                manager = now_time_table.objects.first().name,
                item="studytable",
                message = str(self.number)+"번 테이블 | "+self.start_time+"부터 1시간 빌림"
            )
        super().save(*args, **kwargs)

    def __str__(self):
        return "Table "+str(self.number)


class timetest(models.Model):
    timea = models.DateTimeField(auto_now_add=True)

software-final/HBW/login/models.py
from django.db import models

# Create your models here.

class UserInfo(models.Model):
    name = models.CharField(max_length = 10)
    stdID = models.CharField(max_length = 8)
    HB = models.BooleanField(default = False)

    def __str__(self):
        return self.name
    
    objects = models.Manager()

software-final/HBW/login/forms.py
from django import forms
from .models import UserInfo

class UserForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ('name', 'stdID', 'HB',)


software-final/HBW/login/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import UserInfo
from .forms import UserForm
# Create your views here.

def UserEdit(request, pk):
    user = get_object_or_404(UserInfo, pk=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance = user)
        if form.is_valid() :
            form.save()
            return render(request, 'login/user_edit_detail.html', {'user':user})
    else:
        form = UserForm(instance=user)
    return render(request, 'login/user_edit.html', {'form': form})

def UserShow(request, pk) :
    qs = UserInfo.objects.get(stdID = pk)
    return render(request, 'login/user_show.html', {'user': qs})

login/templates/login/change_pw.html
{% extends 'login/layout.html' %}
{% load staticfiles %}

{% block header %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "login:main" %}">SUPPORT.</a>
      </div>
      <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
              <li><a href="{% url "login:main" %}">홈</a></li>
              {% if user.is_authenticated %}
                <li><a href="{% url "login:logout" %}">로그아웃</a></li>
              {% else %}
                <li><a href="{% url "login:login" %}">로그인</a></li>
              {% endif %}
              <li><a href="{% url "login:seltable" %}">실습실 예약</a></li>
              <li><a href="{% url "login:mypage" %}">마이페이지</a></li>
          </ul>
      </div>
      <!--/.nav-collapse -->
  </div>
</div>
{% endblock %}

{% block content %}
    <!-- *****************************************************************************************************************
	 BLUE WRAP
	 ***************************************************************************************************************** -->
    <div id="blue">
        <div class="container">
            <div class="row">
                <h3>비밀번호 변경</h3>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /blue -->



    <!--Login Form-->

    <div class="container">
        <form action="" method="POST">{% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger"style="margin-top:2.5%; margin-bottom:2.5%;">
                {% for field in form %}
                    {% for error in field.errors %}                        
                            <strong><i class="fas fa-exclamation-circle"></i>　{{ error|escape }}</strong><br>
                        
                    {% endfor %}
                {% endfor %}
                </div>
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong><i class="fas fa-exclamation-circle"></i>　{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            
            <div class="row">
                <div class="input-field ">
                        {{ form.old_password }}
                        <label for="user_id">이전 비밀번호</label>
                </div>
                <div class="input-field ">
                        {{ form.new_password1 }}
                        <label for="user_id">변경 비밀번호</label>
                </div>
                    <div class="input-field ">
                        {{ form.new_password2 }}
                        <label for="user_pw">비밀변호 확인</label>
                </div>
            
                    <p><input type="submit" class="btn btn-theme btn-block" value = "비밀번호 변경"/>

            </div>
        </form>
    </div>
{% endblock %}


    
{% block copyrights %}
    <div id="copyrights">
        <div class="container">
            <p>
                &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
            </p>
            <div class="credits">
                Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
            </div>
        </div>
    </div>
    <!-- / copyrights -->
{% endblock %}

login/templates/login/check.html
<head>
        <meta charset="utf-8">
    <title>소프트웨어 복지사업</title>
</head>

<body> 
        <form action="/login/reservation/" method="post">{% csrf_token %}
            {{ form.selected_table.label_tag }}
            {{ form.selected_table }}
            {{ form.selected_table.errors }}
            <div class="btn_time">
                    <p>
                        <pre>
                            <input type="submit" value="예약 가능시간 확인">												
                        </pre>
                    </p>
                </div>
            </div>
        </form>	
</body>

login/templates/login/item_update.html
{% extends 'login/layout.html' %}
{% load staticfiles %}

{% block header %}
<!-- <select> 태그를 하면 웹상에서 보이지 않아서 <select>태그에 browser-default 클래스 추가해주는 스크립트. 다른 방식으로 보이게만 되면 지워도 됨-->
  <script>
    $(document).ready(function() {
      $('#id_status').addClass('browser-default');
      $('#id_cable_type').addClass('browser-default');
    });
  </script>
{% endblock %}

{% block content %}
  <form method="POST">
      {% csrf_token %}
      {{ form.status.errors }}
      <label for="{{ form.status.id_for_label }}">대여상태 : </label>
      {{ form.status }}

      {{ form.borrowed_by.errors }}
      <label for="{{ form.borrowed_by.id_for_label }}">대여자 : </label>
      {{ form.borrowed_by }}
      
      {{ form.ex_lender.errors }}
      <label for="{{ form.ex_lender.id_for_label }}">기존 대여자 : </label>
      {{ form.ex_lender }}
      
      {% if form.cable_type %}
        {{ form.cable_type.errors }}
        <label for="{{ form.cable_type.id_for_label }}">케이블 타입 : </label>
        {{ form.cable_type }}
      {% endif %}
      <input type="submit" value="수정">
  </form>
    
{% endblock %}

{% block copyrights %}
<div id="copyrights">
  <div class="container">
    <p>
      &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
    </p>
    <div class="credits">
      Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
    </div>
  </div>
</div>
<!-- / copyrights -->
{% endblock %}

login/templates/login/login.html
{% extends 'login/layout.html' %}
{% load staticfiles %}
{% block header %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "login:main" %}">SUPPORT.</a>
    </div>
    <div class="navbar-collapse collapse navbar-right">
      <ul class="nav navbar-nav">
        <li><a href="{% url "login:main" %}">홈</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url "login:logout" %}">로그아웃</a></li>
        {% else %}
        <li class="active"><a href="{% url "login:login" %}">로그인</a></li>
        {% endif %}
        <li><a href="{% url "login:seltable" %}">실습실 예약</a></li>
        <li><a href="{% url "login:mypage" %}">마이페이지</a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</div>
{% endblock %}

{% block content %}
<!-- *****************************************************************************************************************
	 BLUE WRAP
	 ***************************************************************************************************************** -->
<div id="blue" style="margin-bottom:1.5%;">
  <div class="container">
    <div class="row">
      <h3>로그인</h3>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /blue -->



<!--Login Form-->

<div class="container">
  <form action="" method="POST">{% csrf_token %}
    <div class="row">
      {% if form.errors %}
      {% for error in form.non_field_errors %}
      <div class="alert alert-danger" style="margin-top:2.5%; margin-bottom:2.5%;">
        <strong><i class="fas fa-exclamation-circle"></i>　{{ error|escape }}</strong>
      </div>
      {% endfor %}
      {% endif %}

      <div class="col-lg-6 col-lg-offset-3 col-md-12">
        <div class="input-field ">
          {{ form.username }}
          <label for="user_id">아이디</label>
        </div>
        <div class="input-field ">
          {{ form.password }}
          <label for="user_pw">패스워드</label>
        </div>
        <p><input type=submit class="btn btn-theme btn-block" , value="로그인"></input></p>
        <div class="col-lg-12">
          <p>
            <label>
              <input type="checkbox" class="filled-in">
              <span>자동 로그인</span>
            </label>
            <span style="float: right;">　
              <i class="fas fa-question-circle"></i> 비밀번호를 잊었다면 <a href="{% url "login:password_reset" %}">여기로</a><!-- 4/9 비밀번호 초기화 링크 추가(주소는 고쳐서 연결해주세요.)   -->
            </span>
          </p>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block copyrights %}
<div id="copyrights">
  <div class="container">
    <p>
      &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
    </p>
    <div class="credits">
      Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
    </div>
  </div>
</div>
<!-- / copyrights -->
{% endblock %}

login/templates/login/login_base.html
<!Doctype html>
<html lang="en">
        <head>
            <title>
                HBW
            </title>

        </head>
            
        <body>
            <h1>
                HBW Test Page
            </h1>

            {% block content %}
            {% endblock content %}            

        </body>
</html>

login/templates/login/manage.html
{% extends 'login/layout.html' %}
{% load staticfiles %}

{% block header %}
{% endblock %}

{% block content %}
  <a href="{% url 'login:manage_rental' %}">대여사업</a>
  <a href="">포스터</a>
  <a href="">건의사항</a>
  <a href="">공지사항</a>
    
{% endblock %}

{% block copyrights %}
<div id="copyrights">
  <div class="container">
    <p>
      &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
    </p>
    <div class="credits">
      Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
    </div>
  </div>
</div>
<!-- / copyrights -->
{% endblock %}

login/templates/login/password_change_done.html
{% extends 'login/layout.html' %}

{% block header %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "login:main" %}">SUPPORT.</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
            <ul class="nav navbar-nav">
                <li><a href="{% url "login:main" %}">홈</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url "login:logout" %}">로그아웃</a></li>
                {% else %}
                <li class="active"><a href="{% url "login:login" %}">로그인</a></li>
                {% endif %}
                <li><a href="{% url "login:seltable" %}">실습실 예약</a></li>
                <li><a href="{% url "login:mypage" %}">마이페이지</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>
{% endblock %}

{% block content %}
<!-- *****************************************************************************************************************
	 BLUE WRAP
	 ***************************************************************************************************************** -->
<div id="blue">
    <div class="container">
        <div class="row">
            <h3>비밀번호 변경 성공</h3>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /blue -->



<!--Login Form-->

<div class="container">
    <div class="row" style="margin:5%;">
        <!--<span class ="logo_content" ><h3 style="margin-bottom:2%;">언제나, 늘, 당신곁에</h3></span>-->

        <div class="col-lg-12">
            <div class="alert alert-success" role="alert">
                <span>
                    <h3 style="text-align:center;font-size:18px;">비밀번호가 성공적으로 변경되었습니다 <i class="far fa-smile"></i></h3>
                </span>
            </div>
            <a href="/" class="btn btn-theme btn-block" style="font-weight:bold;">홈으로 돌아가기</a>
        </div>
        <!--                
{{ form.as_p }}
                    <p><input type="submit" class="btn btn-theme btn-block" value = "비밀번호 변경"/>
                    <p><a href="{% url "login:main" %}" class="btn btn-theme btn-block">비밀번호 변경</a></p>-->

    </div>
</div>
{% endblock %}



{% block copyrights %}
<div id="copyrights">
    <div class="container">
        <p>
            &copy; Copyrights <strong>Solid</strong>. All Rights Reserved
        </p>
        <div class="credits">
            Created with Solid template by <a href="https://templatemag.com/">TemplateMag</a>
        </div>
    </div>
</div>
<!-- / copyrights -->
{% endblock %}

login/templates/login/user_edit.html
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <hr></hr>
    <button type="submit">수정</button>
</form>

login/templates/login/user_edit_detail.html
<h1>{{ user.name }}</h1>
<h3>{{ user.stdID }}</h3>
<h5>{{ user.HB }}</h5>

login/templates/login/user_show.html
{% extends './login_base.html' %}

{% block content %}
    <div><p>{{ user.name }}</p></div>
    <div><p>{{ user.stdID }}</p></div>
    <div><p>{{ user.HB }}</p></div>
{% endblock content %}            